# Generated by Django 4.2.6 on 2023-10-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shading3dmodel', '0002_filedata_user_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_PDF',
        ),
        migrations.AddField(
            model_name='filedata',
            name='pdffile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
